name = "CreateCore Reforged"
author = "SajmonOriginal"
version = "v1.7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c838c61b1fb8910106807d4f7f4c7f24d2810da376ba94aa13dc9d6a02ef0cc"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
