
#Mod integration config
[Integration]

	#Minecraft
	[Integration.minecraft]

		#Vanilla Minecraft
		[Integration.minecraft.minecraft]
			#Enabled Vanilla Minecraft integration. Default value is true
			enabled = true

	#Create
	[Integration.create]

		#Create Creative Crate
		[Integration.create.creative_crate]
			#Enabled Create Creative Crate integration. Default value is true
			enabled = true
			#Create Creative Crate storage priority. Items are inserted first into storages with higher priority. Default value is 0
			priority = 0

	#Immersive Engineering
	[Integration.immersiveengineering]

		#Immersive Engineering Crate
		[Integration.immersiveengineering.crate]
			#Enabled Immersive Engineering Crate integration. Default value is true
			enabled = true

