
["Toggle model visibility"]
	#Slot 1
	s1 = false
	#Slot 2
	s2 = true
	#Slot 3
	s3 = true
	#Slot 4
	s4 = true
	#Slot 5
	s5 = true
	#Slot 6
	s6 = true
	#Slot 7
	s7 = true
	#Slot 8
	s8 = true
	#Shield
	shield = true
	#Banner
	banner = true

